name: Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release, e.g. 1.2.3"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest
    environment: Default

    steps:
      - name: Checkout tag
        if: github.event_name == 'push'
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Checkout selected tag
        if: github.event_name == 'workflow_dispatch'
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ inputs.version }}

      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 21

      - uses: gradle/actions/setup-gradle@v6

      - name: Publish to Maven Central
        run: ./gradlew publishAndReleaseToMavenCentral
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.SIGNING_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}